//! Session keys for Account Abstraction (ZEP-017).
//!
//! Session keys allow dapps to sign transactions on behalf of users within
//! defined constraints, without requiring a wallet popup for every action.
//!
//! ## Use Cases
//! - **GameFi**: auto-move in games without wallet popup
//! - **SocialFi**: auto-post/auto-like without approval
//! - **DEX bots**: auto-rebalance within defined limits
//! - **Subscriptions**: recurring payments with fixed caps

use serde::{Deserialize, Serialize};
use sha3::{Digest, Sha3_256};
use std::collections::HashMap;
use thiserror::Error;
use zbx_types::address::Address;

// ── Error types ───────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum SessionKeyError {
    #[error("session key {0:?} not registered for wallet {1:?}")]
    KeyNotFound(Address, Address),

    #[error("session key expired: valid_until = {valid_until}, current = {current}")]
    KeyExpired { valid_until: u64, current: u64 },

    #[error("session key not yet valid: valid_from = {valid_from}, current = {current}")]
    KeyNotYetValid { valid_from: u64, current: u64 },

    #[error("target contract {0:?} not in allowed list")]
    ContractNotAllowed(Address),

    #[error("function selector {0:#010x} not in allowed list")]
    SelectorNotAllowed(u32),

    #[error("value {value} wei exceeds per-tx limit {limit} wei")]
    ValueExceedsPerTxLimit { value: u128, limit: u128 },

    #[error("daily spend limit exceeded: used {used} wei, limit {limit} wei")]
    DailyLimitExceeded { used: u128, limit: u128 },

    #[error("daily call count exceeded: used {used}, limit {limit}")]
    DailyCallCountExceeded { used: u64, limit: u64 },

    #[error("session key policy validation failed: {0}")]
    PolicyViolation(String),
}

// ── Session Key Policy ────────────────────────────────────────────────────────

/// Maximum number of session keys per wallet.
pub const MAX_SESSION_KEYS_PER_WALLET: usize = 20;
/// Maximum session key validity period (7 days in seconds).
pub const MAX_SESSION_KEY_DURATION_SECS: u64 = 7 * 24 * 3600;

/// A session key policy defining what the key is allowed to do.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionKeyPolicy {
    /// The ephemeral signing key address (generated by dapp, no private key stored on-chain).
    pub session_key: Address,
    /// The wallet that granted this permission.
    pub wallet:      Address,

    // ── Scope constraints ─────────────────────────────────────────────────────

    /// Allowed target contracts. If empty, any contract is allowed.
    pub allowed_contracts: Vec<Address>,
    /// Allowed function selectors (first 4 bytes of calldata). If empty, any function.
    pub allowed_selectors: Vec<u32>,

    // ── Value constraints ─────────────────────────────────────────────────────

    /// Maximum ZBX value per transaction (in wei). 0 = no value transfers allowed.
    pub max_value_per_tx: u128,
    /// Maximum ZBX spend per day (in wei).
    pub daily_value_limit: u128,
    /// Maximum calls per day (0 = unlimited).
    pub daily_call_limit: u64,

    // ── Time constraints ──────────────────────────────────────────────────────

    /// Unix timestamp when the session key becomes valid.
    pub valid_from: u64,
    /// Unix timestamp when the session key expires (max 7 days from valid_from).
    pub valid_until: u64,

    // ── Metadata ──────────────────────────────────────────────────────────────

    /// Human-readable label (for wallet UI display).
    pub label: String,
    /// Dapp that requested this session key.
    pub dapp_origin: String,
}

impl SessionKeyPolicy {
    /// Create a policy for a gaming dapp (read-only, no value).
    pub fn gaming(
        session_key:  Address,
        wallet:       Address,
        game_contract: Address,
        valid_secs:   u64,
        current_time: u64,
    ) -> Self {
        SessionKeyPolicy {
            session_key,
            wallet,
            allowed_contracts: vec![game_contract],
            allowed_selectors: vec![], // any function in game contract
            max_value_per_tx:  0,      // no value transfers
            daily_value_limit: 0,
            daily_call_limit:  1000,   // max 1000 actions/day
            valid_from:        current_time,
            valid_until:       current_time + valid_secs.min(MAX_SESSION_KEY_DURATION_SECS),
            label:             "Gaming Session".to_string(),
            dapp_origin:       String::new(),
        }
    }

    /// Create a policy for a DEX with daily limits.
    pub fn dex_trading(
        session_key:      Address,
        wallet:           Address,
        dex_contract:     Address,
        daily_limit_wei:  u128,
        valid_secs:       u64,
        current_time:     u64,
    ) -> Self {
        // swap(address,address,uint256,uint256) = 0x38ed1739
        // execute(bytes) = 0x09c5eabe
        let allowed_selectors = vec![0x38ed1739u32, 0x09c5eabeu32];
        SessionKeyPolicy {
            session_key,
            wallet,
            allowed_contracts: vec![dex_contract],
            allowed_selectors,
            max_value_per_tx:  daily_limit_wei / 10, // 10% of daily in one tx
            daily_value_limit: daily_limit_wei,
            daily_call_limit:  100,
            valid_from:        current_time,
            valid_until:       current_time + valid_secs.min(MAX_SESSION_KEY_DURATION_SECS),
            label:             "DEX Trading".to_string(),
            dapp_origin:       String::new(),
        }
    }

    /// Unique ID for this policy = keccak256(wallet || session_key || valid_from).
    pub fn id(&self) -> [u8; 32] {
        let mut h = Sha3_256::new();
        h.update(&self.wallet.0);
        h.update(&self.session_key.0);
        h.update(self.valid_from.to_le_bytes());
        h.finalize().into()
    }
}

// ── Session Key Usage Tracking ────────────────────────────────────────────────

/// Rolling 24-hour usage counters for a session key.
///
/// ## M-09 fix (ZBX-M-09): rolling 24-hour window replaces calendar-day reset
///
/// The old implementation reset counters when `current_time / 86400` changed
/// (UTC midnight boundary).  An attacker could spend the full `daily_value_limit`
/// just before midnight and again just after, effectively doubling the cap in a
/// 2-second window.
///
/// Fix: `window_start` records the Unix timestamp when the CURRENT 24-hour window
/// began.  The window is reset only when `current_time >= window_start + 86400`,
/// which guarantees at least 86400 seconds between any two resets regardless of
/// wall-clock UTC boundaries.  Each reset anchors `window_start` to `current_time`
/// (the moment of reset) rather than to a calendar boundary.
#[derive(Debug, Clone, Default)]
pub struct DailyUsage {
    /// Unix timestamp (seconds) when the current 24-hour window started.
    /// 0 = no usage yet (window starts on first use).
    pub window_start: u64,
    pub value_used:   u128,
    pub calls_made:   u64,
}

impl DailyUsage {
    /// Reset counters if the rolling 24-hour window has elapsed.
    /// Anchors the new window to `current_time` (not to a UTC boundary).
    pub fn reset_if_window_elapsed(&mut self, current_time: u64) {
        if self.window_start == 0 || current_time >= self.window_start + 86400 {
            self.window_start = current_time;
            self.value_used   = 0;
            self.calls_made   = 0;
        }
    }
}

// ── Session Key Validator ─────────────────────────────────────────────────────

/// Validates session key usage against registered policies.
pub struct SessionKeyValidator {
    /// Registered policies: wallet → session_key → policy
    policies: HashMap<[u8; 20], HashMap<[u8; 20], SessionKeyPolicy>>,
    /// Daily usage: policy_id → usage
    usage:    HashMap<[u8; 32], DailyUsage>,
}

impl SessionKeyValidator {
    pub fn new() -> Self {
        SessionKeyValidator {
            policies: HashMap::new(),
            usage:    HashMap::new(),
        }
    }

    /// Register a new session key policy.
    pub fn register(
        &mut self,
        policy: SessionKeyPolicy,
        current_time: u64,
    ) -> Result<[u8; 32], SessionKeyError> {
        // Validate policy
        if policy.valid_until <= policy.valid_from {
            return Err(SessionKeyError::PolicyViolation(
                "valid_until must be after valid_from".into(),
            ));
        }
        if policy.valid_until - policy.valid_from > MAX_SESSION_KEY_DURATION_SECS {
            return Err(SessionKeyError::PolicyViolation(
                format!("duration exceeds maximum {} seconds", MAX_SESSION_KEY_DURATION_SECS),
            ));
        }
        if policy.valid_until < current_time {
            return Err(SessionKeyError::PolicyViolation("already expired".into()));
        }

        let wallet_policies = self.policies
            .entry(policy.wallet.0)
            .or_default();

        if wallet_policies.len() >= MAX_SESSION_KEYS_PER_WALLET {
            return Err(SessionKeyError::PolicyViolation(
                format!("max {} session keys per wallet", MAX_SESSION_KEYS_PER_WALLET),
            ));
        }

        let id = policy.id();
        wallet_policies.insert(policy.session_key.0, policy);
        Ok(id)
    }

    /// Revoke a session key.
    pub fn revoke(
        &mut self,
        wallet:      &Address,
        session_key: &Address,
    ) -> Result<(), SessionKeyError> {
        let wallet_policies = self.policies
            .get_mut(&wallet.0)
            .ok_or_else(|| SessionKeyError::KeyNotFound(*session_key, *wallet))?;
        wallet_policies.remove(&session_key.0)
            .ok_or_else(|| SessionKeyError::KeyNotFound(*session_key, *wallet))?;
        Ok(())
    }

    /// Validate a session key call and update usage counters.
    pub fn validate_call(
        &mut self,
        wallet:       &Address,
        session_key:  &Address,
        target:       &Address,
        selector:     u32,
        value:        u128,
        current_time: u64,
    ) -> Result<(), SessionKeyError> {
        let policy = self.policies
            .get(&wallet.0)
            .and_then(|wp| wp.get(&session_key.0))
            .ok_or_else(|| SessionKeyError::KeyNotFound(*session_key, *wallet))?
            .clone();

        // Time checks
        if current_time < policy.valid_from {
            return Err(SessionKeyError::KeyNotYetValid {
                valid_from: policy.valid_from,
                current:    current_time,
            });
        }
        if current_time > policy.valid_until {
            return Err(SessionKeyError::KeyExpired {
                valid_until: policy.valid_until,
                current:     current_time,
            });
        }

        // Contract scope check
        if !policy.allowed_contracts.is_empty()
            && !policy.allowed_contracts.contains(target)
        {
            return Err(SessionKeyError::ContractNotAllowed(*target));
        }

        // Selector scope check
        if !policy.allowed_selectors.is_empty()
            && !policy.allowed_selectors.contains(&selector)
        {
            return Err(SessionKeyError::SelectorNotAllowed(selector));
        }

        // Per-tx value check
        if value > policy.max_value_per_tx {
            return Err(SessionKeyError::ValueExceedsPerTxLimit {
                value,
                limit: policy.max_value_per_tx,
            });
        }

        // Daily usage checks
        let usage = self.usage.entry(policy.id()).or_default();
        usage.reset_if_window_elapsed(current_time);

        if policy.daily_value_limit > 0
            && usage.value_used + value > policy.daily_value_limit
        {
            return Err(SessionKeyError::DailyLimitExceeded {
                used:  usage.value_used,
                limit: policy.daily_value_limit,
            });
        }

        if policy.daily_call_limit > 0
            && usage.calls_made >= policy.daily_call_limit
        {
            return Err(SessionKeyError::DailyCallCountExceeded {
                used:  usage.calls_made,
                limit: policy.daily_call_limit,
            });
        }

        // All checks passed — update usage
        usage.value_used += value;
        usage.calls_made += 1;

        Ok(())
    }

    /// Get the policy for a session key.
    pub fn get_policy(&self, wallet: &Address, session_key: &Address) -> Option<&SessionKeyPolicy> {
        self.policies.get(&wallet.0)?.get(&session_key.0)
    }

    /// List all active session keys for a wallet.
    pub fn list_keys(&self, wallet: &Address, current_time: u64) -> Vec<&SessionKeyPolicy> {
        self.policies
            .get(&wallet.0)
            .map(|wp| {
                wp.values()
                    .filter(|p| p.valid_until >= current_time)
                    .collect()
            })
            .unwrap_or_default()
    }
}

impl Default for SessionKeyValidator {
    fn default() -> Self { Self::new() }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn addr(n: u8) -> Address { Address([n; 20]) }

    #[test]
    fn register_and_validate_gaming_key() {
        let mut validator = SessionKeyValidator::new();
        let wallet = addr(1);
        let session_key = addr(2);
        let game = addr(3);
        let now = 1_000_000u64;

        let policy = SessionKeyPolicy::gaming(session_key, wallet, game, 3600, now);
        validator.register(policy, now).unwrap();

        // Valid call
        assert!(validator.validate_call(&wallet, &session_key, &game, 0xDEADBEEF, 0, now + 100).is_ok());

        // Wrong contract rejected
        let other = addr(99);
        assert!(matches!(
            validator.validate_call(&wallet, &session_key, &other, 0xDEADBEEF, 0, now + 100),
            Err(SessionKeyError::ContractNotAllowed(_))
        ));
    }

    #[test]
    fn expired_key_rejected() {
        let mut validator = SessionKeyValidator::new();
        let wallet = addr(1);
        let sk = addr(2);
        let game = addr(3);
        let now = 1_000_000u64;

        let policy = SessionKeyPolicy::gaming(sk, wallet, game, 3600, now);
        validator.register(policy, now).unwrap();

        // After expiry
        assert!(matches!(
            validator.validate_call(&wallet, &sk, &game, 0, 0, now + 3601),
            Err(SessionKeyError::KeyExpired { .. })
        ));
    }

    #[test]
    fn dex_daily_limit_enforced() {
        let mut validator = SessionKeyValidator::new();
        let wallet = addr(1);
        let sk = addr(2);
        let dex = addr(3);
        let now = 1_000_000u64;
        let daily_limit = 1_000_000u128; // 1 token unit

        let policy = SessionKeyPolicy::dex_trading(sk, wallet, dex, daily_limit, 3600, now);
        validator.register(policy, now).unwrap();

        // First call: 800K — within limit
        assert!(validator.validate_call(&wallet, &sk, &dex, 0x38ed1739, 800_000, now + 10).is_ok());

        // Second call: 300K more — exceeds 1M daily limit
        assert!(matches!(
            validator.validate_call(&wallet, &sk, &dex, 0x38ed1739, 300_000, now + 20),
            Err(SessionKeyError::DailyLimitExceeded { .. })
        ));
    }

    #[test]
    fn revoke_removes_key() {
        let mut validator = SessionKeyValidator::new();
        let wallet = addr(1);
        let sk = addr(2);
        let game = addr(3);
        let now = 1_000_000u64;

        let policy = SessionKeyPolicy::gaming(sk, wallet, game, 3600, now);
        validator.register(policy, now).unwrap();
        validator.revoke(&wallet, &sk).unwrap();

        assert!(matches!(
            validator.validate_call(&wallet, &sk, &game, 0, 0, now + 10),
            Err(SessionKeyError::KeyNotFound(_, _))
        ));
    }

    #[test]
    fn too_long_duration_rejected() {
        let mut validator = SessionKeyValidator::new();
        let now = 1_000_000u64;
        let policy = SessionKeyPolicy {
            session_key:       addr(2),
            wallet:            addr(1),
            allowed_contracts: vec![],
            allowed_selectors: vec![],
            max_value_per_tx:  0,
            daily_value_limit: 0,
            daily_call_limit:  0,
            valid_from:        now,
            valid_until:       now + MAX_SESSION_KEY_DURATION_SECS + 1, // too long
            label:             "test".into(),
            dapp_origin:       String::new(),
        };
        assert!(matches!(
            validator.register(policy, now),
            Err(SessionKeyError::PolicyViolation(_))
        ));
    }
}
