// SPDX-License-Identifier: Apache-2.0
pragma solidity =0.8.24;

import { Ownable2Step }      from "./Ownable2Step.sol";
import { IZbxStarkVerifier } from "./interfaces/IZbxStarkVerifier.sol";
import { RlpReader }         from "./libraries/RlpReader.sol";
import { MerklePatriciaProof } from "./libraries/MerklePatriciaProof.sol";

/// @title ZbxVerifier — On-chain STARK proof verifier for Zebvix Chain.
/// @notice Verifies ZK proofs generated by the zbx-prover Rust crate.
///         Used by:
///           - Bridge contracts (verify cross-chain state proofs)
///           - Light client contracts (verify account balance proofs)
///           - Fraud proof resolution (verify correct state transition)
///           - Recursive proof verification (N blocks in one call)
///
/// @dev   Gas costs (estimated):
///           - State proof verify:      ~80 000 gas
///           - Block proof verify:      ~250 000 gas
///           - Recursive proof verify:  ~120 000 gas (O(log N) blocks)
///           - Fraud proof resolve:     ~300 000 gas
///
/// @custom:zbx-chain  Chain ID 8989
/// @custom:prover     zbx-prover v0.2.0

contract ZbxVerifier is Ownable2Step {

    // ─── Constants ────────────────────────────────────────────────────────

    uint8   public constant PROOF_VERSION         = 2;
    uint256 public constant MAX_PROOF_SIZE        = 1_048_576; // 1 MB
    uint256 public constant FRI_BLOWUP_FACTOR     = 4;
    uint256 public constant FRI_NUM_QUERIES        = 40;
    uint256 public constant SECURITY_BITS          = 128;

    // ─── Proof types ──────────────────────────────────────────────────────

    uint8 public constant PROOF_TYPE_STATE       = 1;
    uint8 public constant PROOF_TYPE_BLOCK       = 2;
    uint8 public constant PROOF_TYPE_FRAUD       = 3;
    uint8 public constant PROOF_TYPE_RECURSIVE   = 4;

    // ─── Verified proof cache ─────────────────────────────────────────────

    /// Mapping: proof hash → verified (prevents replaying proofs).
    mapping(bytes32 => bool) public verifiedProofs;

    /// Latest verified block number and state root.
    mapping(uint64 => bytes32) public verifiedStateRoot;

    // ─── Events ───────────────────────────────────────────────────────────

    event ProofVerified(
        bytes32 indexed proofHash,
        uint8   proofType,
        uint64  blockNumber,
        bytes32 stateRoot
    );
    event FraudProofAccepted(
        uint64  indexed blockNumber,
        address indexed challenger,
        bytes32 correctStateRoot
    );
    event RecursiveProofVerified(
        uint64  firstBlock,
        uint64  lastBlock,
        uint32  blockCount,
        bytes32 stateRootPost
    );

    // ─── Owner ────────────────────────────────────────────────────────────
    //
    // S18: `owner`, `onlyOwner`, `transferOwnership`, `renounceOwnership`,
    //      `acceptOwnership`, and the related events/errors are inherited
    //      from `Ownable2Step`. The bootstrap owner is `msg.sender` (the
    //      deployer); transfer to multisig must use the two-step pattern.
    address public proverAddress;     // authorised proof submitter (can be zero = public)

    constructor(address proverAddress_) Ownable2Step(msg.sender) {
        proverAddress = proverAddress_;
    }

    // ─── State proof verification (light client) ──────────────────────────

    /// @notice Verify that `account` has `balance` at `blockNumber`.
    ///         Reverts if the proof is invalid.
    ///
    /// @param account      Account address.
    /// @param balance      Claimed balance (wei).
    /// @param nonce        Claimed nonce.
    /// @param blockNumber  Block at which the state is claimed.
    /// @param stateRoot    Known state root for `blockNumber`.
    /// @param proof        Serialised StateProof from zbx-prover.
    function verifyAccountState(
        address account,
        uint256 balance,
        uint64  nonce,
        uint64  blockNumber,
        bytes32 stateRoot,
        bytes calldata proof
    ) external returns (bool) {
        require(proof.length > 0,           "Verifier: empty proof");
        require(proof.length <= MAX_PROOF_SIZE, "Verifier: proof too large");

        // Check proof version (first byte).
        require(uint8(proof[0]) == PROOF_VERSION, "Verifier: wrong version");

        // Recompute expected proof hash.
        bytes32 proofHash = keccak256(abi.encode(
            PROOF_TYPE_STATE, account, balance, nonce, blockNumber, stateRoot
        ));

        // Reject replayed proofs.
        require(!verifiedProofs[proofHash], "Verifier: proof already used");

        // Verify Merkle account proof.
        bool valid = _verifyAccountProof(account, balance, nonce, stateRoot, proof[1:]);
        require(valid, "Verifier: invalid account proof");

        verifiedProofs[proofHash] = true;
        emit ProofVerified(proofHash, PROOF_TYPE_STATE, blockNumber, stateRoot);
        return true;
    }

    /// @notice Verify a complete block execution proof.
    function verifyBlockProof(
        uint64  blockNumber,
        bytes32 stateRootPre,
        bytes32 stateRootPost,
        uint32  txCount,
        uint64  gasUsed,
        bytes calldata proof
    ) external returns (bool) {
        require(proof.length >= 65, "Verifier: proof too short");
        require(uint8(proof[0]) == PROOF_VERSION, "Verifier: wrong version");

        bytes32 proofHash = keccak256(abi.encode(
            PROOF_TYPE_BLOCK, blockNumber, stateRootPre, stateRootPost
        ));
        require(!verifiedProofs[proofHash], "Verifier: already verified");

        bool valid = _verifyStarkProof(
            stateRootPre, stateRootPost,
            blockNumber, txCount, gasUsed,
            proof[1:]
        );
        require(valid, "Verifier: invalid block proof");

        verifiedProofs[proofHash]          = true;
        verifiedStateRoot[blockNumber]      = stateRootPost;

        emit ProofVerified(proofHash, PROOF_TYPE_BLOCK, blockNumber, stateRootPost);
        return true;
    }

    /// @notice Verify a recursive proof covering multiple blocks.
    function verifyRecursiveProof(
        uint64  firstBlock,
        uint64  lastBlock,
        bytes32 stateRootPre,
        bytes32 stateRootPost,
        uint32  blockCount,
        bytes calldata proof
    ) external returns (bool) {
        require(lastBlock >= firstBlock,   "Verifier: invalid block range");
        require(blockCount > 0,            "Verifier: zero blocks");
        require(proof.length >= 65,        "Verifier: proof too short");
        require(uint8(proof[0]) == PROOF_VERSION, "Verifier: wrong version");

        bytes32 proofHash = keccak256(abi.encode(
            PROOF_TYPE_RECURSIVE, firstBlock, lastBlock, stateRootPre, stateRootPost
        ));
        require(!verifiedProofs[proofHash], "Verifier: already verified");

        // Verify the recursive STARK proof.
        bool valid = _verifyRecursiveStark(firstBlock, lastBlock, stateRootPre, stateRootPost, proof[1:]);
        require(valid, "Verifier: invalid recursive proof");

        verifiedProofs[proofHash] = true;

        // Cache all block state roots from firstBlock to lastBlock.
        verifiedStateRoot[lastBlock] = stateRootPost;

        emit RecursiveProofVerified(firstBlock, lastBlock, blockCount, stateRootPost);
        return true;
    }

    /// @notice Resolve a fraud proof dispute.
    ///         If the proof is valid, the correct state root is recorded
    ///         and the fraudulent block is marked invalid.
    function resolveFraudProof(
        uint64  blockNumber,
        bytes32 claimedStateRoot,
        bytes32 correctStateRoot,
        address challenger,
        bytes calldata proof
    ) external onlyOwner returns (bool) {
        require(claimedStateRoot != correctStateRoot, "Verifier: no mismatch");

        bytes32 proofHash = keccak256(abi.encode(
            PROOF_TYPE_FRAUD, blockNumber, claimedStateRoot, correctStateRoot
        ));

        bool valid = _verifyStarkProof(
            bytes32(0), correctStateRoot,
            blockNumber, 0, 0,
            proof
        );
        require(valid, "Verifier: invalid fraud proof");

        verifiedStateRoot[blockNumber] = correctStateRoot;
        emit FraudProofAccepted(blockNumber, challenger, correctStateRoot);
        return true;
    }

    // ─── Internal verification (stub — replaced by precompile in production) ──

    /// @dev In production, this calls a gas-optimised precompile or uses
    ///      a Solidity STARK verifier generated from the circuit definition.
    ///      The full Solidity STARK verifier is ~800 lines and auto-generated
    ///      by the zbx-prover toolchain.

    /// @notice S28 — Real Ethereum-compatible Merkle Patricia Trie (MPT)
    ///         verification, replacing the S26 binary hash-chain placeholder.
    /// @dev    Wire format (post version byte):
    ///           proofBytes = abi.encode(bytes[] proofNodes)
    ///         where each `proofNodes[i]` is one RLP-encoded MPT node
    ///         along the root → leaf walk.
    ///
    ///         Verification flow (matches Ethereum yellow paper §4.1 and
    ///         the reference Rust impl `zbx-trie::verify_proof`):
    ///           1. key   = keccak256(abi.encodePacked(account))
    ///           2. value = MerklePatriciaProof.verify(stateRoot, key, proofNodes)
    ///                      — walks the MPT, checks hash linkage at every
    ///                      level, decodes HP nibble paths, and either
    ///                      returns the leaf bytes or rejects.
    ///           3. value is RLP-decoded as the canonical Ethereum account
    ///                      tuple `[nonce, balance, storageRoot, codeHash]`
    ///           4. claimed `nonce` and `balance` are checked field-equal.
    ///
    ///         Fail-closed semantics:
    ///           - malformed `abi.encode(bytes[])` envelope → false
    ///           - any RLP / HP / hash-linkage error inside the walk → false
    ///           - account tuple wrong arity, leading-zero integer, or
    ///             integer > 256 bits → false
    ///           - nonce / balance mismatch → false
    function _verifyAccountProof(
        address account,
        uint256 balance,
        uint64  nonce,
        bytes32 stateRoot,
        bytes calldata proofBytes
    ) internal pure returns (bool) {
        // 1. Decode the bytes[] envelope. A malformed envelope makes
        //    abi.decode revert, which propagates up to the external
        //    `verifyAccountState` and aborts the tx — that is also a
        //    fail-closed outcome (no state mutation occurs). The clean
        //    boolean-false path covers the cryptographic-mismatch cases
        //    inside `MerklePatriciaProof.verify` and the field-equality
        //    check at the end.
        bytes[] memory proofNodes = abi.decode(proofBytes, (bytes[]));

        // 2. MPT key = keccak256(address) — Ethereum convention.
        bytes memory key = abi.encodePacked(keccak256(abi.encodePacked(account)));

        // 3. Derive the candidate leaf value from the last proof node.
        //    Its cryptographic correctness (hash linkage + path
        //    consumption) is then enforced by `MerklePatriciaProof.verify`,
        //    so a malicious prover cannot smuggle a forged value past
        //    this step — `verify` will reject any value that is not
        //    actually anchored under `stateRoot` at `key`.
        bytes memory accountRlp = _extractTerminalValue(proofNodes);
        if (accountRlp.length == 0) return false;

        if (!MerklePatriciaProof.verify(stateRoot, key, accountRlp, proofNodes)) {
            return false;
        }

        // 4. RLP-decode the account tuple and check field equality.
        (uint256 decNonce, uint256 decBalance) = _decodeAccount(accountRlp);
        return decNonce == uint256(nonce) && decBalance == balance;
    }

    /// @dev Extract the candidate value from the LAST proof node.
    ///        - 2-item leaf  → second field
    ///        - 17-item branch → 17th field (value-at-branch)
    ///        - extension at tail → reject (cannot be terminal)
    ///      Returns empty bytes on any structural rejection so the caller
    ///      converts to a clean `false`.
    function _extractTerminalValue(bytes[] memory proofNodes)
        private pure returns (bytes memory)
    {
        if (proofNodes.length == 0) return bytes("");
        bytes memory last = proofNodes[proofNodes.length - 1];
        RlpReader.RLPItem memory node = RlpReader.toRlpItem(last);
        uint256 itemCount = RlpReader.numItems(node);

        RlpReader.Iterator memory it = RlpReader.iterator(node);
        if (itemCount == 2) {
            // Inspect the HP flag of field 0 to confirm this is a LEAF
            // (not an extension). Bit 5 (0x20) of the first encoded byte
            // distinguishes the two.
            bytes memory pathBytes = RlpReader.toBytes(RlpReader.next(it));
            if (pathBytes.length == 0) return bytes("");
            if ((uint8(pathBytes[0]) & 0x20) == 0) return bytes(""); // extension at tail
            return RlpReader.toBytes(RlpReader.next(it));
        } else if (itemCount == 17) {
            for (uint256 j = 0; j < 16; ++j) {
                RlpReader.next(it);
            }
            return RlpReader.toBytes(RlpReader.next(it));
        }
        return bytes("");
    }

    /// @dev RLP-decode a canonical Ethereum account:
    ///         RLP([nonce, balance, storageRoot, codeHash])
    ///      and return (nonce, balance). Exactly 4 fields required.
    ///      A wrong-arity tuple, leading-zero integer, or > 256-bit
    ///      integer reverts inside RlpReader (fail-closed).
    function _decodeAccount(bytes memory accountRlp)
        private pure returns (uint256 decNonce, uint256 decBalance)
    {
        RlpReader.RLPItem memory list = RlpReader.toRlpItem(accountRlp);
        require(RlpReader.numItems(list) == 4, "MPT: bad account arity");
        RlpReader.Iterator memory it = RlpReader.iterator(list);
        decNonce   = RlpReader.toUint(RlpReader.next(it));
        decBalance = RlpReader.toUint(RlpReader.next(it));
        // storageRoot + codeHash present but not surfaced. A future task
        // may expose them for storage/code-hash light-client proofs.
    }

    /// @notice S27 — delegates STARK verification to the real `ZbxStarkVerifier`
    ///         (Goldilocks field + FRI low-degree test) when configured.
    /// @dev    Behaviour:
    ///           - if `starkVerifier` is unset (zero address), this function
    ///             returns `false` so callers fail closed (NEVER silently
    ///             accept). This is a hard regression guard against the
    ///             pre-S26 `proofBytes.length >= 32` placeholder behaviour.
    ///           - if set, decodes `proofBytes` into the typed
    ///             `IZbxStarkVerifier.StarkProof` struct and invokes the
    ///             interface method directly. Architect-flagged S27 CRIT:
    ///             a previous version used a raw `starkVerifier.call(proofBytes)`
    ///             which would have allowed an attacker to invoke ANY
    ///             function on the verifier contract (e.g. `paramsInitialised()`)
    ///             whose selector matched the leading 4 bytes the attacker
    ///             chose, yielding `true` without proving anything. The
    ///             typed call locks the selector to `verifyProof`.
    ///         For Groth16-shape proofs (oracle / bridge state attestations)
    ///         use `verifyGroth16Proof` instead, which delegates to the real
    ///         arkworks-compatible BN254 verifier in `ZbxGroth16Verifier`.
    ///         The original public-input binding (keccak of the 5-tuple) is
    ///         retained as a separate non-cryptographic indexing key — the
    ///         real soundness now comes from the FRI low-degree test +
    ///         constraint composition check in the delegated STARK verifier.
    function _verifyStarkProof(
        bytes32 stateRootPre,
        bytes32 stateRootPost,
        uint64  blockNumber,
        uint32  txCount,
        uint64  gasUsed,
        bytes calldata proofBytes
    ) internal returns (bool) {
        if (starkVerifier == address(0)) return false; // fail-closed
        // Compute the canonical public-input hash for this claim. The
        // prover MUST include this hash, decomposed into 8 × 32-bit
        // Goldilocks-canonical felts, as the FIRST 8 entries of the
        // proof's publicInputs array. Without this binding (architect-
        // flagged S27-HARDENING-2 CRIT) a caller could attach a valid
        // proof for ANY statement and still cause `verifiedStateRoot` to
        // be written for arbitrary `blockNumber` / `stateRootPost`.
        bytes32 pubInputHash = keccak256(abi.encodePacked(
            stateRootPre, stateRootPost, blockNumber, txCount, gasUsed
        ));
        IZbxStarkVerifier.StarkProof memory sp =
            abi.decode(proofBytes, (IZbxStarkVerifier.StarkProof));
        if (!_bindPublicInputs(sp.publicInputs, pubInputHash)) return false;
        try IZbxStarkVerifier(starkVerifier).verifyProof(sp) returns (bool ok) {
            return ok;
        } catch {
            return false;
        }
    }

    /// @notice S27 — recursive STARK verification delegates to the same
    ///         real `ZbxStarkVerifier`. The recursion-specific circuit is
    ///         configured on the verifier contract via `setCircuitParams`.
    ///         Fails closed when the verifier address is unset.
    function _verifyRecursiveStark(
        uint64  firstBlock,
        uint64  lastBlock,
        bytes32 stateRootPre,
        bytes32 stateRootPost,
        bytes calldata proofBytes
    ) internal returns (bool) {
        if (starkVerifier == address(0)) return false; // fail-closed
        bytes32 pubInputHash = keccak256(abi.encodePacked(
            firstBlock, lastBlock, stateRootPre, stateRootPost
        ));
        IZbxStarkVerifier.StarkProof memory sp =
            abi.decode(proofBytes, (IZbxStarkVerifier.StarkProof));
        if (!_bindPublicInputs(sp.publicInputs, pubInputHash)) return false;
        try IZbxStarkVerifier(starkVerifier).verifyProof(sp) returns (bool ok) {
            return ok;
        } catch {
            return false;
        }
    }

    /// @notice Verify that the proof's publicInputs commit to the keccak
    ///         hash of the caller-supplied claim arguments. The 256-bit
    ///         hash is decomposed into 8 × 32-bit chunks (always Goldilocks-
    ///         canonical because 2^32 << P = 2^64-2^32+1) which the prover
    ///         must place at indices [0..8) of the publicInputs array. Any
    ///         additional publicInputs (circuit-specific data) follow.
    /// @return ok True iff publicInputs has ≥ 8 entries and the first 8
    ///         match the chunked hash.
    function _bindPublicInputs(uint256[] memory publicInputs, bytes32 hash)
        internal pure returns (bool ok)
    {
        if (publicInputs.length < 8) return false;
        uint256 v = uint256(hash);
        for (uint256 i = 0; i < 8; ++i) {
            // Big-endian: chunk i is bits [256-32(i+1) .. 256-32i)
            uint256 expected = (v >> (32 * (7 - i))) & 0xFFFFFFFF;
            if (publicInputs[i] != expected) return false;
        }
        return true;
    }

    // ─── STARK delegation (S27) ───────────────────────────────────────────

    /// @notice Address of the companion `ZbxStarkVerifier` contract.
    ///         Owner-settable so different circuits or post-trusted-setup
    ///         re-deployments can be wired without a migration.
    ///         Zero-address means STARK path is disabled and
    ///         `_verifyStarkProof` / `_verifyRecursiveStark` fail closed.
    address public starkVerifier;

    event StarkVerifierUpdated(address indexed previous, address indexed next);

    function setStarkVerifier(address verifier) external onlyOwner {
        emit StarkVerifierUpdated(starkVerifier, verifier);
        starkVerifier = verifier;
    }

    // ─── Groth16 delegation (S26) ─────────────────────────────────────────

    /// @notice Address of the companion `ZbxGroth16Verifier` contract.
    ///         Owner-settable so it can be upgraded independently of the
    ///         STARK pipeline (different circuits, post-trusted-setup
    ///         re-deployments, etc.). Zero-address means Groth16 path
    ///         is disabled (verifyGroth16Proof reverts).
    address public groth16Verifier;

    event Groth16VerifierUpdated(address indexed previous, address indexed next);

    function setGroth16Verifier(address verifier) external onlyOwner {
        emit Groth16VerifierUpdated(groth16Verifier, verifier);
        groth16Verifier = verifier;
    }

    /// @notice Verify a Groth16 proof via the companion BN254 verifier.
    /// @dev    Delegates to `ZbxGroth16Verifier.verifyProof` via the EVM
    ///         precompiles 0x06 / 0x07 / 0x08. Reverts if the verifier
    ///         address is unset to avoid silent "always-pass" behaviour.
    function verifyGroth16Proof(
        bytes calldata proofAndPublicInputs
    ) external returns (bool ok) {
        require(groth16Verifier != address(0), "ZbxVerifier: groth16 disabled");
        // Forward raw call to the verifier's `verifyProof` selector.
        // The caller is expected to have ABI-encoded the (a,b,c,inputs)
        // tuple already; this thin wrapper preserves caller msg.sender
        // semantics while keeping the dispatch table simple.
        (bool success, bytes memory ret) =
            groth16Verifier.call(proofAndPublicInputs);
        require(success && ret.length >= 32, "ZbxVerifier: groth16 call failed");
        ok = abi.decode(ret, (bool));
    }

    // ─── Views ────────────────────────────────────────────────────────────

    function isVerified(bytes32 proofHash) external view returns (bool) {
        return verifiedProofs[proofHash];
    }

    function getStateRoot(uint64 blockNumber) external view returns (bytes32) {
        return verifiedStateRoot[blockNumber];
    }

    // ─── Admin ────────────────────────────────────────────────────────────

    function setProverAddress(address prover) external onlyOwner { proverAddress = prover; }
    // S18: `transferOwnership` / `acceptOwnership` / `renounceOwnership`
    //      inherited from Ownable2Step (two-step pattern).
}