//! EVM opcode table (London/Shanghai compatible).

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Opcode {
    STOP       = 0x00, ADD        = 0x01, MUL        = 0x02,
    SUB        = 0x03, DIV        = 0x04, SDIV       = 0x05,
    MOD        = 0x06, SMOD       = 0x07, ADDMOD     = 0x08,
    MULMOD     = 0x09, EXP        = 0x0a, SIGNEXTEND = 0x0b,
    LT         = 0x10, GT         = 0x11, SLT        = 0x12,
    SGT        = 0x13, EQ         = 0x14, ISZERO     = 0x15,
    AND        = 0x16, OR         = 0x17, XOR        = 0x18,
    NOT        = 0x19, BYTE       = 0x1a, SHL        = 0x1b,
    SHR        = 0x1c, SAR        = 0x1d,
    SHA3       = 0x20,
    ADDRESS    = 0x30, BALANCE    = 0x31, ORIGIN     = 0x32,
    CALLER     = 0x33, CALLVALUE  = 0x34, CALLDATALOAD = 0x35,
    CALLDATASIZE = 0x36, CALLDATACOPY = 0x37, CODESIZE = 0x38,
    CODECOPY   = 0x39, GASPRICE   = 0x3a, EXTCODESIZE = 0x3b,
    EXTCODECOPY = 0x3c, RETURNDATASIZE = 0x3d, RETURNDATACOPY = 0x3e,
    EXTCODEHASH = 0x3f,
    BLOCKHASH  = 0x40, COINBASE   = 0x41, TIMESTAMP  = 0x42,
    NUMBER     = 0x43, PREVRANDAO = 0x44, GASLIMIT   = 0x45,
    CHAINID    = 0x46, SELFBALANCE = 0x47, BASEFEE   = 0x48,
    POP        = 0x50, MLOAD      = 0x51, MSTORE     = 0x52,
    MSTORE8    = 0x53, SLOAD      = 0x54, SSTORE     = 0x55,
    JUMP       = 0x56, JUMPI      = 0x57, PC         = 0x58,
    MSIZE      = 0x59, GAS        = 0x5a, JUMPDEST   = 0x5b,
    PUSH0      = 0x5f, // EIP-3855 (Shanghai)
    PUSH1      = 0x60, PUSH2 = 0x61, PUSH3 = 0x62, PUSH4 = 0x63,
    PUSH5      = 0x64, PUSH6 = 0x65, PUSH7 = 0x66, PUSH8 = 0x67,
    PUSH9      = 0x68, PUSH10 = 0x69, PUSH11 = 0x6a, PUSH12 = 0x6b,
    PUSH13     = 0x6c, PUSH14 = 0x6d, PUSH15 = 0x6e, PUSH16 = 0x6f,
    PUSH17     = 0x70, PUSH18 = 0x71, PUSH19 = 0x72, PUSH20 = 0x73,
    PUSH21     = 0x74, PUSH22 = 0x75, PUSH23 = 0x76, PUSH24 = 0x77,
    PUSH25     = 0x78, PUSH26 = 0x79, PUSH27 = 0x7a, PUSH28 = 0x7b,
    PUSH29     = 0x7c, PUSH30 = 0x7d, PUSH31 = 0x7e, PUSH32 = 0x7f,
    DUP1       = 0x80, DUP2 = 0x81, DUP3 = 0x82, DUP4 = 0x83,
    DUP5       = 0x84, DUP6 = 0x85, DUP7 = 0x86, DUP8 = 0x87,
    DUP9       = 0x88, DUP10 = 0x89, DUP11 = 0x8a, DUP12 = 0x8b,
    DUP13      = 0x8c, DUP14 = 0x8d, DUP15 = 0x8e, DUP16 = 0x8f,
    SWAP1      = 0x90, SWAP2 = 0x91, SWAP3 = 0x92, SWAP4 = 0x93,
    SWAP5      = 0x94, SWAP6 = 0x95, SWAP7 = 0x96, SWAP8 = 0x97,
    SWAP9      = 0x98, SWAP10 = 0x99, SWAP11 = 0x9a, SWAP12 = 0x9b,
    SWAP13     = 0x9c, SWAP14 = 0x9d, SWAP15 = 0x9e, SWAP16 = 0x9f,
    LOG0       = 0xa0, LOG1 = 0xa1, LOG2 = 0xa2, LOG3 = 0xa3, LOG4 = 0xa4,
    CREATE     = 0xf0, CALL = 0xf1, CALLCODE = 0xf2, RETURN = 0xf3,
    DELEGATECALL = 0xf4, CREATE2 = 0xf5, STATICCALL = 0xfa,
    REVERT     = 0xfd, INVALID = 0xfe, SELFDESTRUCT = 0xff,
}

impl Opcode {
    /// Map a raw byte to an `Opcode` variant.
    ///
    /// NEW-CRIT-02 FIX (2026-05-03): Previously 16 valid EVM opcodes were
    /// missing from this table (SDIV, MOD, SMOD, ADDMOD, MULMOD, EXP,
    /// SIGNEXTEND, SLT, SGT, BYTE, SAR, ORIGIN, EXTCODESIZE, EXTCODECOPY,
    /// EXTCODEHASH, INVALID), causing them to be dispatched as
    /// `EvmError::InvalidOpcode` and silently halting any contract that used
    /// them — including all standard Solidity-generated bytecode.
    pub fn from_u8(b: u8) -> Option<Self> {
        Some(match b {
            0x00 => Opcode::STOP,       0x01 => Opcode::ADD,
            0x02 => Opcode::MUL,        0x03 => Opcode::SUB,
            0x04 => Opcode::DIV,        0x05 => Opcode::SDIV,
            0x06 => Opcode::MOD,        0x07 => Opcode::SMOD,
            0x08 => Opcode::ADDMOD,     0x09 => Opcode::MULMOD,
            0x0a => Opcode::EXP,        0x0b => Opcode::SIGNEXTEND,
            0x10 => Opcode::LT,         0x11 => Opcode::GT,
            0x12 => Opcode::SLT,        0x13 => Opcode::SGT,
            0x14 => Opcode::EQ,         0x15 => Opcode::ISZERO,
            0x16 => Opcode::AND,        0x17 => Opcode::OR,
            0x18 => Opcode::XOR,        0x19 => Opcode::NOT,
            0x1a => Opcode::BYTE,       0x1b => Opcode::SHL,
            0x1c => Opcode::SHR,        0x1d => Opcode::SAR,
            0x20 => Opcode::SHA3,
            0x30 => Opcode::ADDRESS,    0x31 => Opcode::BALANCE,
            0x32 => Opcode::ORIGIN,     0x33 => Opcode::CALLER,
            0x34 => Opcode::CALLVALUE,  0x35 => Opcode::CALLDATALOAD,
            0x36 => Opcode::CALLDATASIZE, 0x37 => Opcode::CALLDATACOPY,
            0x38 => Opcode::CODESIZE,   0x39 => Opcode::CODECOPY,
            0x3a => Opcode::GASPRICE,   0x3b => Opcode::EXTCODESIZE,
            0x3c => Opcode::EXTCODECOPY, 0x3d => Opcode::RETURNDATASIZE,
            0x3e => Opcode::RETURNDATACOPY, 0x3f => Opcode::EXTCODEHASH,
            0x40 => Opcode::BLOCKHASH,  0x41 => Opcode::COINBASE,
            0x42 => Opcode::TIMESTAMP,  0x43 => Opcode::NUMBER,
            0x44 => Opcode::PREVRANDAO, 0x45 => Opcode::GASLIMIT,
            0x46 => Opcode::CHAINID,    0x47 => Opcode::SELFBALANCE,
            0x48 => Opcode::BASEFEE,
            0x50 => Opcode::POP,        0x51 => Opcode::MLOAD,
            0x52 => Opcode::MSTORE,     0x53 => Opcode::MSTORE8,
            0x54 => Opcode::SLOAD,      0x55 => Opcode::SSTORE,
            0x56 => Opcode::JUMP,       0x57 => Opcode::JUMPI,
            0x58 => Opcode::PC,         0x59 => Opcode::MSIZE,
            0x5a => Opcode::GAS,        0x5b => Opcode::JUMPDEST,
            0x5f => Opcode::PUSH0,
            0x60..=0x7f => Opcode::PUSH1, // PUSH1–PUSH32 handled specially
            0x80..=0x8f => Opcode::DUP1,  // DUP1–DUP16
            0x90..=0x9f => Opcode::SWAP1, // SWAP1–SWAP16
            0xa0 => Opcode::LOG0, 0xa1 => Opcode::LOG1,
            0xa2 => Opcode::LOG2, 0xa3 => Opcode::LOG3, 0xa4 => Opcode::LOG4,
            0xf0 => Opcode::CREATE,     0xf1 => Opcode::CALL,
            0xf2 => Opcode::CALLCODE,   0xf3 => Opcode::RETURN,
            0xf4 => Opcode::DELEGATECALL, 0xf5 => Opcode::CREATE2,
            0xfa => Opcode::STATICCALL,
            0xfd => Opcode::REVERT,     0xfe => Opcode::INVALID,
            0xff => Opcode::SELFDESTRUCT,
            _ => return None,
        })
    }

    pub fn static_gas(&self) -> u64 {
        use crate::gas::*;
        match self {
            Opcode::STOP | Opcode::RETURN | Opcode::REVERT => GAS_ZERO,
            // SHA3 and LOG* are fully dynamic — static portion is zero so the
            // handler can charge the correct data/topic-dependent cost in full.
            Opcode::SHA3 | Opcode::LOG0 | Opcode::LOG1 | Opcode::LOG2
            | Opcode::LOG3 | Opcode::LOG4 => GAS_ZERO,
            Opcode::ADD | Opcode::SUB | Opcode::NOT | Opcode::LT | Opcode::GT
            | Opcode::SLT | Opcode::SGT | Opcode::EQ | Opcode::ISZERO
            | Opcode::AND | Opcode::OR | Opcode::XOR | Opcode::BYTE
            | Opcode::SHL | Opcode::SHR | Opcode::SAR
            | Opcode::CALLDATALOAD | Opcode::CALLDATASIZE | Opcode::CODESIZE
            | Opcode::RETURNDATASIZE | Opcode::ADDRESS | Opcode::CALLER
            | Opcode::CALLVALUE | Opcode::GASPRICE | Opcode::COINBASE
            | Opcode::TIMESTAMP | Opcode::NUMBER | Opcode::PREVRANDAO
            | Opcode::GASLIMIT | Opcode::CHAINID | Opcode::BASEFEE
            | Opcode::MLOAD | Opcode::MSTORE | Opcode::MSTORE8
            | Opcode::POP | Opcode::PC | Opcode::MSIZE | Opcode::GAS
            | Opcode::PUSH0 | Opcode::PUSH1 => GAS_VERY_LOW,
            Opcode::MUL | Opcode::DIV | Opcode::SDIV | Opcode::MOD
            | Opcode::SMOD | Opcode::SIGNEXTEND => GAS_LOW,
            Opcode::ADDMOD | Opcode::MULMOD | Opcode::JUMP => GAS_MID,
            Opcode::EXP => GAS_ZERO, // fully dynamic: 10 + 50 * byte_len(exp)
            Opcode::JUMPI | Opcode::BLOCKHASH => GAS_HIGH,
            Opcode::JUMPDEST => GAS_JUMPDEST,
            Opcode::BALANCE | Opcode::SELFBALANCE => GAS_SLOAD_WARM,
            Opcode::ORIGIN | Opcode::EXTCODESIZE | Opcode::EXTCODEHASH => GAS_SLOAD_WARM,
            Opcode::SLOAD  => GAS_SLOAD_WARM,  // warm; cold adds 2000 in handler
            Opcode::SSTORE => 0,               // fully dynamic
            Opcode::EXTCODECOPY => GAS_SLOAD_WARM, // warm base; dynamic copy+cold
            Opcode::CODECOPY | Opcode::CALLDATACOPY | Opcode::RETURNDATACOPY => GAS_VERY_LOW,
            // S32 — both CREATE and CREATE2 carry the 32000 base.
            Opcode::CREATE | Opcode::CREATE2 => GAS_CREATE,
            Opcode::CALL | Opcode::CALLCODE | Opcode::DELEGATECALL
            | Opcode::STATICCALL => GAS_CALL,
            // S32 — SELFDESTRUCT gas is paid entirely inside the handler.
            Opcode::SELFDESTRUCT | Opcode::INVALID => 0,
            // PUSH2-PUSH32, DUP1-DUP16, SWAP1-SWAP16 — all GAS_VERY_LOW.
            _ => GAS_VERY_LOW,
        }
    }
}
