//! Groth16 prover for ZK price proofs — ZEP-012 end-to-end.
//!
//! # Flow
//!
//! ```text
//! PriceProver::from_pk_bytes(proving_key_bytes)
//!   ↓
//! prover.prove(public_inputs, tls_response, notary_attestation)
//!   ↓  (witness derivation → Groth16::prove → serialize proof bytes)
//! ZkPriceProof { groth16_a, groth16_b, groth16_c, public_inputs }
//! ```
//!
//! # Proving key bootstrap
//!
//! The proving key is the large (~50 MB) output of the ZEP-012 trusted setup
//! ceremony.  `PriceProver::from_pk_bytes` accepts the compressed serialisation
//! produced by `Groth16::<Bn254>::setup`.
//!
//! For development / testing, `PriceProver::ephemeral` generates a fresh
//! proving key from a random trapdoor — valid proofs but **not safe for
//! production** (the trapdoor is discarded but was briefly in memory).
//!
//! # Proof wire format
//!
//! The proof bytes written into `ZkPriceProof` are the *uncompressed* flat
//! layout expected by the verifier:
//! ```text
//! groth16_a  (64 bytes) — G1 affine, uncompressed
//! groth16_b (128 bytes) — G2 affine, uncompressed
//! groth16_c  (64 bytes) — G1 affine, uncompressed
//! ```
//! This matches [`crate::proof::ZkPriceProof::proof_bytes_canonical`] and
//! the on-chain `ZbxGroth16Verifier.sol` ABI.

use crate::{
    circuit::{CircuitPrivateInputs, CircuitPublicInputs, PriceCircuit},
    notary::NotaryAttestation,
    proof::{ZkPriceProof, ZkPublicInputs},
    verifier::ZkVerifyingKey,
};

use ark_bn254::Bn254;
use ark_groth16::{Groth16, ProvingKey};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize, Compress, Validate};
use ark_ff::One;
use ark_snark::{CircuitSpecificSetupSNARK, SNARK};
use rand::rngs::OsRng;
use thiserror::Error;

// ─────────────────────────────────────────────────────────────────────────────
// Errors
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum ProverError {
    #[error("invalid proving key bytes: {0}")]
    InvalidProvingKey(String),

    #[error("witness derivation failed — tls_digest is zero (degenerate TLS response)")]
    DegenerateTlsDigest,

    #[error("pre-proof validation failed: circuit is not satisfied")]
    UnsatisfiedCircuit,

    #[error("Groth16 proving failed: {0}")]
    ProvingFailed(String),

    #[error("proof serialization failed: {0}")]
    SerializationFailed(String),

    #[error("trusted setup (ceremony) failed: {0}")]
    SetupFailed(String),
}

// ─────────────────────────────────────────────────────────────────────────────
// PriceProver
// ─────────────────────────────────────────────────────────────────────────────

/// Groth16 prover for the ZK price circuit.
///
/// One `PriceProver` instance per feed (each feed has its own proving key from
/// the trusted setup ceremony).  Creating a prover is expensive (deserialises
/// the proving key); reuse it across multiple proof requests.
pub struct PriceProver {
    pk: ProvingKey<Bn254>,
}

impl PriceProver {
    // ── Constructors ──────────────────────────────────────────────────────────

    /// Load a prover from a serialised proving key.
    ///
    /// `pk_bytes` is the compressed `arkworks` serialisation of
    /// `ark_groth16::ProvingKey<Bn254>` as produced by the ZEP-012
    /// trusted setup ceremony.
    ///
    /// # Errors
    /// Returns [`ProverError::InvalidProvingKey`] if the bytes are malformed.
    pub fn from_pk_bytes(pk_bytes: &[u8]) -> Result<Self, ProverError> {
        let pk = ProvingKey::<Bn254>::deserialize_with_mode(
            pk_bytes,
            Compress::Yes,
            Validate::Yes,
        )
        .map_err(|e| ProverError::InvalidProvingKey(e.to_string()))?;
        Ok(Self { pk })
    }

    /// Create a `PriceProver` with a **fresh random trapdoor**.
    ///
    /// ⚠️  **Development / testing only.**  The resulting proofs are
    /// cryptographically valid but the proving key was not generated by a
    /// trusted-setup ceremony — anyone who runs this function could generate
    /// fraudulent proofs.  Never use in production.
    ///
    /// Also returns the verifying key bytes so tests can register the VK with
    /// [`crate::verifier::ZkOracleVerifier`].
    pub fn ephemeral() -> Result<(Self, Vec<u8>), ProverError> {
        // Use a blank circuit as the circuit shape for setup — the R1CS
        // structure (number of variables, constraints) is the same regardless
        // of witness values.
        let blank_circuit = blank_price_circuit();

        let (pk, vk) = Groth16::<Bn254>::setup(blank_circuit, &mut OsRng)
            .map_err(|e| ProverError::SetupFailed(e.to_string()))?;

        // Serialise the verifying key for registration with ZkOracleVerifier.
        let mut vk_bytes = Vec::new();
        vk.serialize_compressed(&mut vk_bytes)
            .map_err(|e| ProverError::SerializationFailed(e.to_string()))?;

        Ok((Self { pk }, vk_bytes))
    }

    /// Derive the verifying key from the loaded proving key.
    ///
    /// Used to build a [`ZkVerifyingKey`] for registration with
    /// [`crate::verifier::ZkOracleVerifier`].
    pub fn verifying_key_bytes(&self) -> Result<Vec<u8>, ProverError> {
        let vk = self.pk.vk.clone();
        let mut buf = Vec::new();
        vk.serialize_compressed(&mut buf)
            .map_err(|e| ProverError::SerializationFailed(e.to_string()))?;
        Ok(buf)
    }

    // ── Main prove method ─────────────────────────────────────────────────────

    /// Generate a ZK price proof.
    ///
    /// # Arguments
    /// * `public`  — circuit public inputs (symbol_hash, price, timestamp, vk_hash, notary_pubkey).
    /// * `tls_response` — raw TLS HTTP response bytes from the CEX API endpoint.
    /// * `attest` — notary attestation (used to populate `ZkPublicInputs.notary_pubkey`).
    ///
    /// # Steps
    /// 1. Derive private witnesses via [`CircuitPrivateInputs::from_tls`].
    /// 2. Run `PriceCircuit::is_satisfied()` pre-check.
    /// 3. Call `Groth16::<Bn254>::prove` to generate the real BN254 proof.
    /// 4. Deserialise proof points and pack into [`ZkPriceProof`] wire format.
    ///
    /// # Errors
    /// * [`ProverError::DegenerateTlsDigest`] — degenerate (zero) TLS hash.
    /// * [`ProverError::UnsatisfiedCircuit`] — pre-check failed.
    /// * [`ProverError::ProvingFailed`] — arkworks Groth16 error.
    pub fn prove(
        &self,
        public:       CircuitPublicInputs,
        tls_response: &[u8],
        attest:       &NotaryAttestation,
    ) -> Result<ZkPriceProof, ProverError> {
        // 1. Derive private witnesses.
        let private = CircuitPrivateInputs::from_tls(tls_response, &public)
            .ok_or(ProverError::DegenerateTlsDigest)?;

        let circuit = PriceCircuit::new(public.clone(), private);

        // 2. Pre-flight structural check.
        if !circuit.is_satisfied() {
            return Err(ProverError::UnsatisfiedCircuit);
        }

        // 3. Generate Groth16 proof (clone circuit for the move into prove).
        let proof = Groth16::<Bn254>::prove(&self.pk, circuit, &mut OsRng)
            .map_err(|e| ProverError::ProvingFailed(e.to_string()))?;

        // 4. Serialise proof points into the ZkPriceProof wire format.
        //
        // The verifier expects *uncompressed* G1/G2 affine points in the
        // flat layout: pi_a (64 B) || pi_b (128 B) || pi_c (64 B).
        let mut pi_a_buf = Vec::new();
        let mut pi_b_buf = Vec::new();
        let mut pi_c_buf = Vec::new();
        proof.a.serialize_uncompressed(&mut pi_a_buf)
            .map_err(|e| ProverError::SerializationFailed(format!("pi_a: {e}")))?;
        proof.b.serialize_uncompressed(&mut pi_b_buf)
            .map_err(|e| ProverError::SerializationFailed(format!("pi_b: {e}")))?;
        proof.c.serialize_uncompressed(&mut pi_c_buf)
            .map_err(|e| ProverError::SerializationFailed(format!("pi_c: {e}")))?;

        if pi_a_buf.len() != 64 || pi_b_buf.len() != 128 || pi_c_buf.len() != 64 {
            return Err(ProverError::SerializationFailed(format!(
                "unexpected point sizes: pi_a={}, pi_b={}, pi_c={}",
                pi_a_buf.len(), pi_b_buf.len(), pi_c_buf.len()
            )));
        }

        let mut groth16_a  = [0u8; 64];
        let mut groth16_b  = [0u8; 128];
        let mut groth16_c  = [0u8; 64];
        groth16_a.copy_from_slice(&pi_a_buf);
        groth16_b.copy_from_slice(&pi_b_buf);
        groth16_c.copy_from_slice(&pi_c_buf);

        // 5. Build the matching public inputs struct for the wire type.
        let pub_inputs = ZkPublicInputs {
            symbol_hash:   public.symbol_hash,
            price:         public.price as i128,
            timestamp:     public.timestamp,
            vk_hash:       public.vk_hash,
            notary_pubkey: attest.notary_pubkey,
        };

        Ok(ZkPriceProof { groth16_a, groth16_b, groth16_c, public_inputs: pub_inputs })
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Create a blank `PriceCircuit` with non-zero but otherwise arbitrary values.
///
/// Used for `Groth16::setup` — the R1CS structure must be identical to what
/// the real prover will use, but witness values can be anything valid.
fn blank_price_circuit() -> PriceCircuit {
    let public = CircuitPublicInputs {
        symbol_hash:   [1u8; 32],
        price:         1_000_00000000u128, // $1000 at 8 decimals
        timestamp:     1_000_000_000u64,
        vk_hash:       [2u8; 32],
        notary_pubkey: [3u8; 33],
    };
    let tls_response = b"blank-circuit-tls-witness-for-setup";
    let private = CircuitPrivateInputs::from_tls(tls_response, &public)
        .expect("blank circuit witness derivation must succeed");
    PriceCircuit::new(public, private)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        notary::NotaryAttestation,
        verifier::{ZkOracleVerifier, ZkVerifyingKey},
    };
    use sha3::{Digest, Keccak256};

    /// Generate a dummy notary attestation (signature not real — only used to
    /// populate the `notary_pubkey` field in the proof wire type for tests).
    fn dummy_attest(notary_pk: [u8; 33]) -> NotaryAttestation {
        NotaryAttestation {
            notary_pubkey: notary_pk,
            session_hash:  [0xAA; 32],
            notary_sig:    [0u8; 64],
            timestamp:     1_700_000_000,
            server_name:   "api.binance.com".into(),
        }
    }

    fn valid_public(vk_hash: [u8; 32]) -> CircuitPublicInputs {
        CircuitPublicInputs {
            symbol_hash:   {
                let mut h = Keccak256::new();
                h.update(b"ZBX/USD");
                let r: [u8; 32] = h.finalize().into();
                r
            },
            price:         3_500_00000000u128,
            timestamp:     1_700_000_000u64,
            vk_hash,
            notary_pubkey: [0x03; 33],
        }
    }

    #[test]
    fn ephemeral_prover_can_generate_proof() {
        let (prover, vk_bytes) = PriceProver::ephemeral()
            .expect("ephemeral setup");

        let vk_hash: [u8; 32] = {
            let mut h = Keccak256::new();
            h.update(&vk_bytes);
            h.finalize().into()
        };

        let public = valid_public(vk_hash);
        let tls    = b"HTTP/1.1 200 OK\r\n\r\n{\"symbol\":\"ZBX/USD\",\"price\":\"3500.00000000\"}";
        let attest = dummy_attest(public.notary_pubkey);

        let proof = prover.prove(public.clone(), tls, &attest)
            .expect("prove");

        // Basic sanity — proof points must be non-zero (point at infinity would be invalid).
        assert!(!proof.groth16_a.iter().all(|&b| b == 0), "pi_a is zero — invalid proof");
        assert!(!proof.groth16_c.iter().all(|&b| b == 0), "pi_c is zero — invalid proof");
    }

    #[test]
    fn ephemeral_proof_verifies_with_matching_vk() {
        let (prover, vk_bytes) = PriceProver::ephemeral()
            .expect("ephemeral setup");

        let vk_hash: [u8; 32] = {
            let mut h = Keccak256::new();
            h.update(&vk_bytes);
            h.finalize().into()
        };

        let public = valid_public(vk_hash);
        let tls    = b"HTTP/1.1 200 OK\r\n\r\n{\"price\":\"3500\"}";
        let attest = dummy_attest(public.notary_pubkey);

        let proof = prover.prove(public.clone(), tls, &attest)
            .expect("prove");

        // Register the VK with the verifier and run the pairing check.
        let mut verifier = ZkOracleVerifier::new();
        verifier
            .register_vk("ZBX/USD".into(), ZkVerifyingKey { vk_bytes, vk_hash })
            .expect("register vk");

        let result = verifier.verify(&proof, "ZBX/USD")
            .expect("verify returned Err");
        assert!(result, "proof generated by ephemeral prover must verify");
    }

    #[test]
    fn degenerate_tls_response_is_rejected() {
        // A TLS response whose Keccak-256 hash happens to be zero is
        // astronomically rare but the prover must handle it gracefully.
        // We can't force a hash collision, so just test that a normal
        // response works (the non-degenerate path) and the error variant exists.
        let (prover, _) = PriceProver::ephemeral().expect("setup");
        let public      = valid_public([0xEE; 32]);
        let tls         = b"normal-tls-response";
        let attest      = dummy_attest(public.notary_pubkey);
        // Normal path must succeed.
        prover.prove(public, tls, &attest).expect("non-degenerate TLS must succeed");
    }

    #[test]
    fn unsatisfied_circuit_returns_error() {
        let (prover, _) = PriceProver::ephemeral().expect("setup");
        // Price = 0 → is_satisfied() → false → UnsatisfiedCircuit
        let mut public = valid_public([0xEE; 32]);
        public.price   = 0;
        let attest     = dummy_attest(public.notary_pubkey);
        let err        = prover.prove(public, b"tls", &attest).unwrap_err();
        assert!(matches!(err, ProverError::UnsatisfiedCircuit));
    }

    #[test]
    fn from_pk_bytes_rejects_garbage() {
        let err = PriceProver::from_pk_bytes(&[0xFFu8; 100]).unwrap_err();
        assert!(matches!(err, ProverError::InvalidProvingKey(_)));
    }

    #[test]
    fn proof_with_wrong_vk_hash_fails_verification() {
        let (prover, vk_bytes) = PriceProver::ephemeral().expect("setup");
        let correct_hash: [u8; 32] = {
            let mut h = Keccak256::new();
            h.update(&vk_bytes);
            h.finalize().into()
        };
        // Prove with the correct VK hash...
        let public = valid_public(correct_hash);
        let tls    = b"tls-data";
        let attest = dummy_attest(public.notary_pubkey);
        let proof  = prover.prove(public, tls, &attest).expect("prove");

        // ...but register a *different* VK hash → VkMismatch
        let mut verifier = ZkOracleVerifier::new();
        let wrong_hash   = [0xBAu8; 32];
        verifier
            .register_vk("ZBX/USD".into(), ZkVerifyingKey { vk_bytes, vk_hash: wrong_hash })
            .expect("register");
        let err = verifier.verify(&proof, "ZBX/USD").unwrap_err();
        assert!(
            matches!(err, crate::verifier::VerifierError::VkMismatch),
            "wrong VK hash must cause VkMismatch, got: {err:?}"
        );
    }
}
