// SPDX-License-Identifier: Apache-2.0
pragma solidity =0.8.24;

/// @title  IZbxTimelock — minimum surface ZbxGovernor calls on the timelock
/// @notice Only the per-tx queue/execute/cancel triple plus the public-state
///         getters Governor needs (delay, GRACE_PERIOD, queuedTransactions,
///         admin). The full ZbxTimelock ABI (setDelay, setPendingAdmin,
///         acceptAdmin, NewDelay/NewAdmin events, etc.) is intentionally
///         NOT mirrored here — Governor never calls those.
///
/// @dev    Signatures track `contracts/ZbxTimelock.sol` exactly:
///           queueTransaction(address, uint256, string, bytes, uint256)
///                returns (bytes32)
///           executeTransaction(address, uint256, string, bytes, uint256)
///                payable returns (bytes memory)
///           cancelTransaction(address, uint256, string, bytes, uint256)
///         Because ZbxTimelock guards every mutator with `onlyAdmin`, the
///         deployment checklist MUST set the timelock's admin to the
///         Governor address (or to a multisig that delegates queueing to
///         the Governor) before any proposal can be queued.
///
/// @custom:zbx-chain  Chain ID 8989
/// @custom:since      S37-governor-timelock (AUDIT C-19 closure, 2026-05-02)
interface IZbxTimelock {
    // ─── Queue / cancel / execute ──────────────────────────────────────

    /// @notice Queue a transaction; returns the keccak256 txHash.
    /// @dev    `eta` MUST be >= block.timestamp + delay() — the timelock
    ///         enforces this and reverts `EtaTooSoon` otherwise.
    function queueTransaction(
        address target,
        uint256 value,
        string calldata signature,
        bytes   calldata data,
        uint256 eta
    ) external returns (bytes32 txHash);

    /// @notice Cancel a previously-queued transaction. Idempotent
    ///         w.r.t. already-cancelled txs only in that the timelock
    ///         reverts `TxNotQueued`. Governor swallows that revert
    ///         when cancelling a Queued proposal so partial-loop
    ///         cancellation cannot brick the proposer's escape hatch.
    function cancelTransaction(
        address target,
        uint256 value,
        string calldata signature,
        bytes   calldata data,
        uint256 eta
    ) external;

    /// @notice Execute a queued transaction; forwards `value` ETH.
    /// @dev    Reverts `TxNotReady` while `block.timestamp < eta`,
    ///         `TxStale` after `eta + GRACE_PERIOD`, and
    ///         `CallReverted(returnData)` on target revert.
    function executeTransaction(
        address target,
        uint256 value,
        string calldata signature,
        bytes   calldata data,
        uint256 eta
    ) external payable returns (bytes memory returnData);

    // ─── Public state getters (auto-generated by Solidity) ─────────────

    /// @notice Current execution delay (seconds). Governor reads this
    ///         dynamically so an in-protocol `setDelay` proposal does
    ///         not require a Governor redeployment.
    function delay() external view returns (uint256);

    /// @notice Window after `eta` during which `executeTransaction`
    ///         remains callable; reads as the timelock's compile-time
    ///         constant (14 days at the time of S37).
    function GRACE_PERIOD() external view returns (uint256);

    /// @notice Whether `txHash` is currently queued. Useful for off-
    ///         chain UIs and post-execution invariants.
    function queuedTransactions(bytes32 txHash) external view returns (bool);

    /// @notice Current admin (must be Governor or a Governor-delegating
    ///         multisig for any proposal to be queueable).
    function admin() external view returns (address);

    // ─── Admin handover (OPERATOR-03 wiring) ───────────────────────────

    /// @notice Accept the pending-admin role.
    ///         Called by the Governor via `acceptTimelockAdmin()` during
    ///         the deployment wiring sequence:
    ///           1. timelock.setPendingAdmin(address(governor))
    ///           2. governor.acceptTimelockAdmin()   ← calls this
    ///         After step 2, `admin()` returns `address(governor)` and
    ///         `verifySetup()` returns `(true, "")`.
    function acceptAdmin() external;
}
